---
abstract: 'Tapper - Frontend web application based on Catalyst'
author:
  - 'Copyright 2008-2011 AMD OSRC Tapper Team, all rights reserved.'
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Deep: 0
  Test::Perl::Critic: 0
  Test::WWW::Mechanize::Catalyst: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: freebsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tapper-Reports-Web
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Controller::BindLex: 0
  Catalyst::Controller::HTML::FormFu: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session: 0.31
  Catalyst::Plugin::Session::State::Cookie: 0.17
  Catalyst::Plugin::Session::Store::File: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.80032
  Catalyst::Test: 0
  Catalyst::View::Mason: 0.18
  Class::C3::Adopt::NEXT: 0
  Data::DPath: 0.42
  DateTime::Format::DateParse: 0
  DateTime::Format::Natural: 0
  DateTime::Format::Strptime: 0
  DateTime::Format::W3CDTF: 0
  FCGI: 0
  File::Copy::Recursive: 0
  File::Find: 0
  File::Find::Rule: 0
  FindBin: 0
  Getopt::Long: 0
  HTML::FormFu: 0
  Hash::Merge: 0
  Pod::Usage: 0
  TAP::Formatter::HTML: 0.04
  TAP::Parser: 0
  Tapper::Cmd: 3.000010
  Tapper::Config: 3.000010
  Tapper::Model: 3.000010
  Tapper::Schema: 3.000010
  Tapper::TAP::Harness: 3.000010
  Tapper::Test: 3.000010
  Tapper::Testplan: 3.000010
  Test::Fixture::DBIC::Schema: 0
  Test::More: 0
  XML::Feed: 0
  YAML: 0.72
  YAML::Syck: 1.17
  common::sense: 0
  parent: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Tapper-Reports-Web
  repository: git://github.com/amd/Tapper-Reports-Web.git
version: 3.000010
